FindingAddress/Models/Lawyer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FindingAddress.Models
{
    public class Lawyer
    {
        public string Id { set; get; }
        public string Name { set; get; }
        public string Gender { set; get; }
        public string imagePath { set; get; }
        public string CourtId { set; get; }
        public string LawyerTypeId { set; get; }
        public string DivisionId { set; get; }
        public string CityId { set; get; }
        public string DistrictId { set; get; }
        public string ThanaId { set; get; }
        public string LocationId { set; get; }
        public Double EstimatedFee { set; get; }
        public string PersonalEmailaddress { set; get; }
        public string PersonalWebsite { set; get; }
        public string PersonalChamber { set; get; }
        public string ContactNumber { set; get; }        
        public string ChamberTime { set; get; }
        public string Education { set; get; }
        public string Description { set; get; }
        public string Address { set; get; }
    }
}

FindingAddress/Controllers/LawyerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FindingAddress.DataAccessLayer;
using FindingAddress.Models;
namespace FindingAddress.Controllers
{
    public class LawyerController : Controller
    {
        //
        // GET: /Lawyer/
        public ActionResult saveLawyer()
        {
            DropDownGateway dropDownGateway = new DropDownGateway();
            ViewBag.CityDropDownList = dropDownGateway.getCityDopdownList();
            ViewBag.DivisionDropdownList = dropDownGateway.getDivisionDopdownList();
            ViewBag.LawyerTypeList = dropDownGateway.getLawerTypeDopdownList();
            ViewBag.CourstList = dropDownGateway.GetCourtsList();
            return View();
            
        }
        [HttpPost]
        public ActionResult saveLawyer(Lawyer lawyer)
        {
            if (ModelState.IsValid)
            {
                LawyerGateway lawyerGateway=new LawyerGateway();
                if (lawyerGateway.saveLawyer(lawyer) > 0)
                {
                    List<Lawyer> lawyers=new List<Lawyer>();
                    lawyers = lawyerGateway.GetAllLayers();
                    return View("showAllLayer", lawyers);
                }
            }
            DropDownGateway dropDownGateway = new DropDownGateway();
            ViewBag.CityDropDownList = dropDownGateway.getCityDopdownList();
            ViewBag.DivisionDropdownList = dropDownGateway.getDivisionDopdownList();
            ViewBag.LawyerTypeList = dropDownGateway.getLawerTypeDopdownList();
            ViewBag.CourstList = dropDownGateway.GetCourtsList();
            return View();

        }
        [HttpGet]
        public ActionResult showAllLayer()
        {
            LawyerGateway lawyerGateway = new LawyerGateway();
            List<Lawyer> lawyers = new List<Lawyer>();
            lawyers = lawyerGateway.GetAllLayers();
            return View(lawyers);
        }
        public ActionResult showLayerDtails(int id)
        {
            LawyerGateway lawyerGateway = new LawyerGateway();
          var  lawyer = lawyerGateway.GetLawyerDetails(id);
          return View(lawyer);
        }
         public JsonResult getDistrictDropdownListByDivisionId(int DivisionId)
        {
            var DistrictList = new List<SelectListItem>();
            if (DivisionId != 0)
            {
                DropDownGateway dropDownGateway = new DropDownGateway();
                DistrictList = dropDownGateway.getDistrictDopdownListByDiisionId(DivisionId);
            }
            else
            {
                RedirectToAction("");
            }
            return Json(new SelectList(DistrictList, "Value", "Text"));

        }
        public JsonResult getThanaDropdownListByDistrictId(int DistrictId)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            if (DistrictId != 0)
            {
                DropDownGateway dropDownGateway = new DropDownGateway();
                list = dropDownGateway.getThanaDopdownListByDistrictId(DistrictId);
            }

            return Json(new SelectList(list, "Value", "Text"));
        }

        public JsonResult getLocationDropdownListByThanaId(int ThanaId)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            if (ThanaId != 0)
            {
                DropDownGateway dropDownGateway = new DropDownGateway();
                list = dropDownGateway.getLocationDopdownListByThanaId(ThanaId);
            }

            return Json(new SelectList(list, "Value", "Text"));
        }
    }
}

FindingAddress/Views/Lawyer/saveLawyer.cshtml
@model FindingAddress.Models.Lawyer

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>saveLawyer</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="panel panel-default">
            <div class="panel-heading">Lawyer Information</div>
            <div class="panel-body">
                <div class="form-horizontal">
                    <h4 style="text-align: center; ">Enter Lawyer details</h4>
                    <hr />
                    @Html.ValidationSummary(true)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Name)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Gender, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Gender, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Gender)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.imagePath, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="imagePath" />
                            @Html.ValidationMessageFor(model => model.imagePath)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CourtId, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.CourtId, ViewBag.CourstList as IEnumerable<SelectListItem>, "SELECT", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CourtId)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LawyerTypeId, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.LawyerTypeId, ViewBag.LawyerTypeList as IEnumerable<SelectListItem>, "SELECT", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.LawyerTypeId)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DivisionId, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.DivisionId, ViewBag.DivisionDropdownList as IEnumerable<SelectListItem>, "SELECT", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.DivisionId)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CityId, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.CityId, ViewBag.CityDropDownList as IEnumerable<SelectListItem>, "SELECT", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CityId)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DistrictId, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select id="DistrictId" class="form-control" name="DistrictId">
                                <option selected="selected">SELECT</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.DistrictId)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.ThanaId, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select id="ThanaId" class="form-control" name="ThanaId">
                                <option selected="selected">SELECT</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.ThanaId)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LocationId, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select id="LocationId" class="form-control" name="LocationId">
                                <option selected="selected">SELECT</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.LocationId)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.EstimatedFee, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.EstimatedFee, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.EstimatedFee)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PersonalEmailaddress, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.PersonalEmailaddress, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.PersonalEmailaddress)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PersonalWebsite, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.PersonalWebsite, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.PersonalWebsite)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PersonalChamber, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.PersonalChamber, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.PersonalChamber)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ContactNumber, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.ContactNumber, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ContactNumber)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ChamberTime, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.ChamberTime, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ChamberTime)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Education, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Education, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Education)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Description)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Address)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
</div>
    }
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#DivisionId').change(function () {
                $.ajax({
                    type: 'post',
                    url: '@Url.Action("getDistrictDropdownListByDivisionId")',
                    dataType: 'json',
                    data: { DivisionId: $("#DivisionId").val() },

                    success: function (data) {
                        $("#DistrictId").empty();
                        $("#DistrictId").append('<option value="' + 0 + '">' + "SELECT" + '</option>');
                        $(data).each(function (index, item) {

                            $("#DistrictId").append('<option value="' + item.Value + '">' + item.Text + '</option>');

                        });
                    }
                });
            });
            $('#DistrictId').change(function () {
                $.ajax({
                    type: 'post',
                    url: '@Url.Action("getThanaDropdownListByDistrictId")',
                    dataType: 'json',
                    data: { DistrictId: $("#DistrictId").val() },

                    success: function (data) {
                        $("#ThanaId").empty();
                        $("#ThanaId").append('<option value="' + 0 + '">' + "SELECT" + '</option>');
                        $(data).each(function (index, item) {

                            $("#ThanaId").append('<option value="' + item.Value + '">' + item.Text + '</option>');

                        });
                    }
                });
            });
            $('#ThanaId').change(function () {
                $.ajax({
                    type: 'post',
                    url: '@Url.Action("getLocationDropdownListByThanaId")',
                    dataType: 'json',
                    data: { ThanaId: $("#ThanaId").val() },

                    success: function (data) {
                        $("#LocationId").empty();
                        $("#LocationId").append('<option value="' + 0 + '">' + "SELECT" + '</option>');
                        $(data).each(function (index, item) {

                            $("#LocationId").append('<option value="' + item.Value + '">' + item.Text + '</option>');

                        });
                    }
                });

            });

        })
    </script>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

FindingAddress/Views/Lawyer/showAllLayer.cshtml
@model IEnumerable<FindingAddress.Models.Lawyer>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>showAllLayer</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstimatedFee)
            </th>
            
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.EstimatedFee)
            </td>
            
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "showLayerDtails", "Lawyer",new { id = item.Id },null) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

FindingAddress/Views/Lawyer/showLayerDtails.cshtml
@model FindingAddress.Models.Lawyer


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Show Layer Dtails</title>
</head>
<body>
    <div>
    <hr />
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">Details</div>
                <div class="panel-body">
                    <table class="table-hover">
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.Name)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.Name)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.Gender)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.Gender)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.imagePath)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.imagePath)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.CourtId)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.CourtId)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.LawyerTypeId)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.LawyerTypeId)
                            </td>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.DivisionId)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.DivisionId)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.CityId)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.CityId)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.DistrictId)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.DistrictId)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.ThanaId)
                            </td>
                            <td>:</td>
                            <td>
                              @Html.DisplayFor(model => model.ThanaId)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.LocationId)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.LocationId)
                            </td>
                        </tr>
                        <tr>
                            <td>
                               @Html.DisplayNameFor(model => model.EstimatedFee)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.EstimatedFee)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.PersonalEmailaddress)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.PersonalEmailaddress)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.PersonalWebsite)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.PersonalWebsite)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.PersonalChamber)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.PersonalChamber)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.ContactNumber)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.ContactNumber)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.ChamberTime)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.ChamberTime)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.Address)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.Address)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.Education)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.Education)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.Description)
                            </td>
                            <td>:</td>
                            <td>
                                @Html.DisplayFor(model => model.Description)
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        
    
          
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>