FindingAddress/Controllers/BusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using FindingAddress.Models;
using FindingAddress.DataAccessLayer;
namespace FindingAddress.Controllers
{
    public class BusController : Controller
    {
        //
        // GET: /Bus/
        [HttpGet]
        public ActionResult saveBus()
        {
            return View();
        }
        [HttpPost]
        public ActionResult saveBus(BusCompany busCompany)
        {
            if (ModelState.IsValid)
            {
                var busCompanyGateway = new BUsCompanyGateway();
                int result = busCompanyGateway.saveBusCompany(busCompany);
                if (result > 0)
                {
                    var busCompanyList = busCompanyGateway.getAllBusCompany();
                    return View("busCompanyDetails", busCompanyList);
                }
                else
                {
                    ViewBag.result = "This bus company already exits";
                }
            }
            return View();
        }
        public ActionResult busCompanyDetails()
        {
            var busCompanyGateway = new BUsCompanyGateway();
            var busCompanyList = busCompanyGateway.getAllBusCompany();
            return View(busCompanyList);
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var busCompanyGateway = new BUsCompanyGateway();
            var busCompany = busCompanyGateway.getBusCompanyById(Id);
            return View(busCompany);
        }
        [HttpPost]
        public ActionResult Edit(BusCompany buscompany)
        {
            var busCompanyGateway = new BUsCompanyGateway();
            int result = busCompanyGateway.updateBusCompanyById(buscompany);
            if (result != -1)
            {
                var busCompany = busCompanyGateway.getAllBusCompany();
                return View("busCompanyDetails", busCompany);
            }
            else
            {
                ViewBag.result = "Updataing faild";
                return View();
            }

        }
        [HttpGet]
        public ActionResult saveBusStatiopn()
        {
            return View();
        }
        [HttpPost]
        public ActionResult saveBusStatiopn(BusStation busStation)
        {
            if (ModelState.IsValid)
            {
                var busStationGateway = new BusStationGateway();
                if (busStationGateway.saveBusStation(busStation) > 0)
                {
                    var busStationList = busStationGateway.getAllBusstation();
                    return View("showBusStationList", busStationList);
                }
            }
            return View();
        }
        public ActionResult showBusStationList()
        {
            return View();
        }
        public ActionResult EditBusStation(int Id)
        {
            var busStationGateway = new BusStationGateway();
            var busStation = busStationGateway.getBusstationById(Id);
            return View(busStation);
        }
        [HttpGet]
        public ActionResult assignBusStation()
        {
            var dropdownGateway = new DropDownGateway();
            ViewBag.buscompanyDropdownList = dropdownGateway.getBusCompanyDopdownList();
            ViewBag.busStationDropdownList = dropdownGateway.gertBusStationDropdownList();
            return View();
        }
        [HttpPost]
        public ActionResult assignBusStation(BusAssignStation busAssignStation)
        {
            var dropdownGateway = new DropDownGateway();
            ViewBag.buscompanyDropdownList = dropdownGateway.getBusCompanyDopdownList();
            ViewBag.busStationDropdownList = dropdownGateway.gertBusStationDropdownList();
            if (ModelState.IsValid)
            {
                var busStationGateway = new BusStationGateway();
                if (busStationGateway.saveBusAssignStation(busAssignStation) > 0)
                {
                    var busAssignStationLst = busStationGateway.getBusAssignStation();
                    return View("ShowassignBusStation", busAssignStationLst);
                }
                else
                {
                    ViewBag.result = "Failed";
                    return View();
                }

            }
            else
            {
                return View();
            }

        }
        public ActionResult ShowassignBusStation()
        {
            var busStationGateway = new BusStationGateway();
            var busAssignStationLst = busStationGateway.getBusAssignStation();
            return View(busAssignStationLst);
        }
        [HttpGet]
        public ActionResult GetBusByBusStation()
        {
            var busStationGateway = new BusStationGateway();
            var busAssignStationLst = busStationGateway.getBusAssignStation();
            return View();
        }
        [HttpPost]
        public ActionResult GetBusByBusStation(BusAssignStation busAssignStation)
        {
            var busStationGateway = new BusStationGateway();
            var busAssignStationLst = busStationGateway.getAllBusCompanyBySourceAndDestination(busAssignStation);
            ViewBag.List = busAssignStationLst;
            return View();
        }
        public JsonResult getStationList(string term)
        {
            var busStationGateway = new BusStationGateway();
            var stationList = busStationGateway.getBusstationNameByName(term);
            return Json(stationList, JsonRequestBehavior.AllowGet);
        }
        public JsonResult searchBusCompanyBySourceAndDestination(BusAssignStation busAssignStation)
        {
            var busStationGateway = new BusStationGateway();
            var stationList = busStationGateway.getAllBusCompanyBySourceAndDestination(busAssignStation);
            return Json(stationList, JsonRequestBehavior.AllowGet);
        }
    }
}

FindingAddress/Views/Bus/Edit.cshtml
@model FindingAddress.Models.BusCompany

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
     <div class="panel panel-success">
     <div class="panel-heading" style="text-align: center">Edit Bus Company</div>
         <div class="panel-body">
             <div class="row">
                 <div class="col-md-offset-2">
                     <div class="form-horizontal">
                         <h4>BusCompany</h4>
                         <hr />
                         @Html.ValidationSummary(true)
                         @Html.HiddenFor(model => model.Id)

                         <div class="form-group">
                             @Html.LabelFor(model => model.CompanyName, new { @class = "control-label col-md-2" })
                             <div class="col-md-10">
                                 @Html.TextBoxFor(model => model.CompanyName, new { @class = "form-control" })
                                 @Html.ValidationMessageFor(model => model.CompanyName)
                             </div>
                         </div>

                         <div class="form-group">
                             @Html.LabelFor(model => model.BusName, new { @class = "control-label col-md-2" })
                             <div class="col-md-10">
                                 @Html.TextBoxFor(model => model.BusName, new { @class = "form-control" })
                                 @Html.ValidationMessageFor(model => model.BusName)
                             </div>
                         </div>

                         <div class="form-group">
                             @Html.LabelFor(model => model.Route, new { @class = "control-label col-md-2" })
                             <div class="col-md-10">
                                 @Html.TextBoxFor(model => model.Route, new { @class = "form-control" })
                                 @Html.ValidationMessageFor(model => model.Route)
                             </div>
                         </div>

                         <div class="form-group">
                             @Html.LabelFor(model => model.OwnerName, new { @class = "control-label col-md-2" })
                             <div class="col-md-10">
                                 @Html.TextBoxFor(model => model.OwnerName, new { @class = "form-control" })
                                 @Html.ValidationMessageFor(model => model.OwnerName)
                             </div>
                         </div>

                         <div class="form-group">
                             @Html.LabelFor(model => model.OwnerContactInformation, new { @class = "control-label col-md-2" })
                             <div class="col-md-10">
                                 @Html.TextAreaFor(model => model.OwnerContactInformation, new { @class = "form-control" })
                                 @Html.ValidationMessageFor(model => model.OwnerContactInformation)
                             </div>
                         </div>

                         <div class="form-group">
                             <div class="col-md-offset-2 col-md-10">
                                 <input type="submit" value="Update" class="btn btn-default" />
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
             
         </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FindingAddress/Views/Bus/EditBusStation.cshtml
@model FindingAddress.DataAccessLayer.BusStation

<br />
<br />
<h3 style="text-align:center">@ViewBag.result</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="panel panel-success">
     <div class="panel-heading" style="text-align: center">Edit Bus Staion</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-offset-2">
                    <div class="form-horizontal">
                        @Html.HiddenFor(model => model.Id)
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Name)
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Location, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Location, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Location)
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
           
        </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FindingAddress/Views/Bus/GetBusByBusStation.cshtml
@using FindingAddress.Models
@model FindingAddress.Models.BusAssignStation

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetBusByBusStation</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="panel panel-primary">
            <div class="panel-heading" style="text-align: center">Find Your Bus</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-offset-2">
                        <div class="form-horizontal">
                            <hr />
                            @Html.ValidationSummary(true)

                            <div class="form-group">
                                @Html.LabelFor(model => model.SourceId, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.SourceId, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.SourceId)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.DestinationId, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.DestinationId, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.DestinationId)
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Search" class="btn btn-default" id="btnSearch" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    <div>
            @if (IsPost)
            {
                <table class="table table-primary">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.BusId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SourceId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DestinationId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Fare)
                        </th>
                    </tr>

                    @foreach (BusAssignStation item in @ViewBag.List)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.BusId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SourceId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DestinationId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Fare)
                            </td>
                        </tr>
                    }

                </table>
            }

    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#SourceId").autocomplete({
                source: 'getStationList'
            });
            $("#DestinationId").autocomplete({
                source: 'getStationList'
            });
            $("btnSearch").click(function () {
                $.ajax({
                    type: 'POST',
                    url: 'searchBusCompanyBySourceAndDestination',
                    dataType: 'json',
                    data: {
                        SourceId: $("#SourceId").val(),
                        DestinationId: $("#DestinationId").val()
                    },
                    success: function (data) {
                        alert('im back');
                        alert(data);
                    },
                    error: function (xhr, ajaxOptions, error) {
                        alert(xhr.status);
                        alert('Error: ' + xhr.responseText);
                    }
                });
            });
        })
    </script>
</body>
</html>

FindingAddress/Views/Bus/ShowassignBusStation.cshtml
@model IEnumerable<FindingAddress.Models.BusAssignStation>

<h2>ShowassignBusStation</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BusId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SourceId)
        </th>
        <th>
            @Html.DisplayNameFor(model=>model.DestinationId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fare)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BusId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SourceId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DestinationId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fare)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

FindingAddress/Views/Bus/assignBusStation.cshtml
@model FindingAddress.Models.BusAssignStation


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
       
    <div class="panel panel-default">
    <div class="panel-heading" style="text-align: center">Bus Assign To Station</div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-offset-2">
                <div class="form-horizontal">
      
                    <h3 style="text-align:center">@ViewBag.result</h3>
                    <hr />
                    @Html.ValidationSummary(true)

                    <div class="form-group">
                        @Html.LabelFor(model => model.BusId, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.BusId, ViewBag.buscompanyDropdownList as IEnumerable<SelectListItem>, "SELECT", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.BusId)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SourceId, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.SourceId, ViewBag.busStationDropdownList as IEnumerable<SelectListItem>, "SELECT", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.SourceId)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.DestinationId, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.DestinationId, ViewBag.busStationDropdownList as IEnumerable<SelectListItem>, "SELECT", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.DestinationId)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Fare, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Fare, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Fare)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Assign" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FindingAddress/Views/Bus/busCompanyDetails.cshtml
@model IEnumerable<FindingAddress.Models.BusCompany>

<h2 style="text-align: center">bus Company Details</h2>
<hr/>
<p>
    @Html.ActionLink("Create New Bus Station", "saveBus","Bus")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BusName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Route)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OwnerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OwnerContactInformation)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BusName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Route)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OwnerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OwnerContactInformation)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

FindingAddress/Views/Bus/saveBus.cshtml
@model FindingAddress.Models.BusCompany

<br />
 <br />
<h3 style="text-align:center;color: red">@ViewBag.result</h3>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="panel panel-default">
    <div class="panel-heading" style="text-align: center">Save Bus Company</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-offset-2">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true)

                        <div class="form-group">
                            @Html.LabelFor(model => model.CompanyName, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.CompanyName, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.CompanyName)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.BusName, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.BusName, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.BusName)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Route, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Route, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Route)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.OwnerName, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.OwnerName, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.OwnerName)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.OwnerContactInformation, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.OwnerContactInformation, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.OwnerContactInformation)
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FindingAddress/Views/Bus/saveBusStatiopn.cshtml
@model FindingAddress.DataAccessLayer.BusStation

<br />
<br />
<h3 style="text-align:center">@ViewBag.result</h3>
@using (Html.BeginForm())
        {
    @Html.AntiForgeryToken()
           
    <div class="panel panel-success">
        <div class="panel-heading" style="text-align: center">Bus Staion</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-offset-2">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true)
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Name)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Location, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Location, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Location)
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>

                    </div>
                </div>
            </div>
           
        </div>
    </div>
    }
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>