FindingAddress/Models/TourSpotImage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FindingAddress.Models
{
    public class TourSpotImage
    {
        public string Id { set; get; }
        public string ImagePath { set; get; }
        public string PhotoCreditName { set; get; }
        public float TourSpotId { set; get; }
        public string UploadDate { set; get; }
    }
}

FindingAddress/Controllers/TourSpotImageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FindingAddress.Models;
using FindingAddress.DataAccessLayer;
namespace FindingAddress.Controllers
{
    public class TourSpotImageController : Controller
    {
        //
        // GET: /TourSpotImage/
        public ActionResult saveTourSoptImage()
        {
            DropDownGateway dropDownGateway=new DropDownGateway();
            ViewBag.TourSpotList = dropDownGateway.GeTourSpotDropDownList();
            return View();
        }
        [HttpPost]
        public ActionResult saveTourSoptImage(TourSpotImage tourSpotImage, HttpPostedFileBase ImagePath)
        {
            if (ImagePath != null)
            {
                string picPath = System.IO.Path.GetFileName(ImagePath.FileName);
                string path = System.IO.Path.Combine(Server.MapPath("~/Images"), picPath);
                tourSpotImage.ImagePath = "~/Images/" + picPath;
                ImagePath.SaveAs(path);
                TourSpotImageGateway tourGateway = new TourSpotImageGateway();
                tourGateway.saveTourSpotImage(tourSpotImage);
            }
            DropDownGateway dropDownGateway = new DropDownGateway();
            ViewBag.TourSpotList = dropDownGateway.GeTourSpotDropDownList();
            return View();
        }
        [HttpGet]
        public ActionResult saveTourSpot()
        {
            return View();
        }
        [HttpPost]
        public ActionResult saveTourSpot(TourSpot tourSpot)
        {
            return View();
        }
	}
}

FindingAddress/Views/TourSpotImage/saveTourSoptImage.cshtml
@model FindingAddress.Models.TourSpotImage

@{
    ViewBag.Title = "saveTourSoptImage";
}

<h2>saveTourSoptImage</h2>

@using (Html.BeginForm("saveTourSoptImage","TourSpotImage",FormMethod.Post,new {enctype="multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TourSpotImage</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImagePath" id="ImagePath"/>
                @Html.ValidationMessageFor(model => model.ImagePath)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhotoCreditName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PhotoCreditName)
                @Html.ValidationMessageFor(model => model.PhotoCreditName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TourSpotId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TourSpotId, ViewBag.TourSpotList as IEnumerable<SelectListItem>, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TourSpotId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FindingAddress/Views/TourSpotImage/saveTourSpot.cshtml
@model FindingAddress.Models.TourSpot

@{
    ViewBag.Title = "saveTourSpot";
}

<h2>saveTourSpot</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TourSpot</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId,ViewBag.categoryDropdown as IEnumerable<SelectListItem>)
                @Html.ValidationMessageFor(model => model.CategoryId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DivisionId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DivisionId)
                @Html.ValidationMessageFor(model => model.DivisionId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DistrctId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DistrctId)
                @Html.ValidationMessageFor(model => model.DistrctId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityId)
                @Html.ValidationMessageFor(model => model.CityId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThanaId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThanaId)
                @Html.ValidationMessageFor(model => model.ThanaId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LocationId)
                @Html.ValidationMessageFor(model => model.LocationId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>