FindingAddress/Models/Hospital.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FindingAddress.Models
{
    public class Hospital
    {
        public string Id { set; get; }
        public string Name { set; get; }
        public string HospitalTypeId { set; get; }
        public string DivisionId { set; get; }
        public string DistrictId { set; get; }
        public string CityId { set; get; }
        public string ThanaId { set; get; }
        public string LocationId { set; get; }
        public string Description { set; get; }
        public string Address { set; get; }
    }
}

FindingAddress/Models/HospitalType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FindingAddress.Models
{
    public class HospitalType
    {
        public string Id { set; get; }
        public string Name { set; get; }
        public string Description { set; get; }
    }
}

FindingAddress/Controllers/HospitalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FindingAddress.DataAccessLayer;
using FindingAddress.Models;

namespace FindingAddress.Controllers
{
    public class HospitalController : Controller
    {
        //
        // GET: /Hospital/
        [HttpGet]
        public ActionResult saveHospitalType()
        {
            return View();
        }
         [HttpPost]
        public ActionResult saveHospitalType(HospitalType hospitalType)
        {
             if (ModelState.IsValid)
             {
                 HospitalGateway hospitalGateway = new HospitalGateway();
                 if (hospitalGateway.saveHospitalType(hospitalType) > 0)
                 {
                     var hospitalTypeList = hospitalGateway.GetHospitalTypes();
                     return View("showHospitaType", hospitalTypeList);
                 }
                 else
                 {
                     return ViewBag.result = "Already exits this name in the list";
                 }
             }
             else
             {
                 return View();
             }
            
        }
         public ActionResult showHospitaType()
         {
             HospitalGateway hospitalGateway = new HospitalGateway();
             var hospitalTypeList = hospitalGateway.GetHospitalTypes();
             return View(hospitalTypeList);
         }
         public ActionResult saveHospitalService()
         {
             return View();
         }
         [HttpPost]
         public ActionResult saveHospitalService(HospitalService hospitalService)
         {
             if (ModelState.IsValid)
             {
                 HospitalGateway hospitalGateway = new HospitalGateway();
                 if (hospitalGateway.saveHospitalService(hospitalService) > 0)
                 {
                     var hospitalServiceList = hospitalGateway.getHospitalServices();
                     return View("showHospitalService", hospitalServiceList);
                 }
                 else
                 {
                     return ViewBag.result = "Already exits this name in the list";
                 }
             }
             else
             {
                 return View();
             }
         }
         public ActionResult showHospitalService()
         {
             HospitalGateway hospitalGateway = new HospitalGateway();
             var hospitalServicesList = hospitalGateway.getHospitalServices();
             return View(hospitalServicesList);
         }
        public ActionResult saveHospital()
        {
            DropDownGateway dropDownGateway = new DropDownGateway();
            ViewBag.DivisionList = dropDownGateway.getDivisionDopdownList();
            ViewBag.getHospitalList = dropDownGateway.getHospitalList();
            ViewBag.getDoctorTypeDopdownList = dropDownGateway.getDoctorTypeDopdownList();
            return View();
        }
        [HttpPost]
        public ActionResult saveHospital(Hospital hospital)
        {
            if (ModelState.IsValid)
            {
                HospitalGateway hospitalGateway = new HospitalGateway();
                if (hospitalGateway.saveHospital(hospital) > 0)
                {
                    var hospitalList = hospitalGateway.GetAllHospitals();
                    return View("showHospital",hospitalList);
                }
            }
            DropDownGateway dropDownGateway = new DropDownGateway();
            ViewBag.DivisionList = dropDownGateway.getDivisionDopdownList();
            ViewBag.cityList = dropDownGateway.getCityDopdownList();
            ViewBag.HospitalTypeDropdownList = dropDownGateway.getHospitalTypeDopdownList();
            return View();
        }
        public ActionResult showHospital()
        {
            HospitalGateway hospitalGateway = new HospitalGateway();
            var hospitalList = hospitalGateway.GetAllHospitals();
            return View(hospitalList);
        }
        public JsonResult getDistrictDropdownListByDivisionId(int DivisionId)
        {
            var DistrictList = new List<SelectListItem>();
            if (DivisionId != 0)
            {
                DropDownGateway dropDownGateway = new DropDownGateway();
                DistrictList = dropDownGateway.getDistrictDopdownListByDiisionId(DivisionId);
            }
            else
            {
                RedirectToAction("saveTourSpot");
            }
            return Json(new SelectList(DistrictList, "Value", "Text"));

        }
        [HttpGet]
        public ActionResult saveHospitalServiceAllocation()
        {
            DropDownGateway dropDownGateway = new DropDownGateway();
            ViewBag.divisionList = dropDownGateway.getDivisionDopdownList();
            ViewBag.ServiceList= dropDownGateway.gertServicesList();
            return View();
        }
        [HttpPost]
        public ActionResult saveHospitalServiceAllocation(HospitalServiceAllocation hospitalServiceAllocation)
         {
            if (ModelState.IsValid)
            {
                HospitalGateway hospitalGateway = new HospitalGateway();
                if (hospitalGateway.savehospitalServiceAllocation(hospitalServiceAllocation) > 0)
                {
                    var hospitalServiceAllocations = hospitalGateway.GetHospitalServiceAllocations();
                    return View("showHospitalServiceAllocation", hospitalServiceAllocations);
                }
                else
                {
                    ViewBag.result = "Already assiged this service with this Hospital";
                }
            }
            DropDownGateway dropDownGateway = new DropDownGateway();
            ViewBag.divisionList = dropDownGateway.getDivisionDopdownList();
            ViewBag.ServiceList = dropDownGateway.gertServicesList();
            return View();
        }
        public ActionResult showHospitalServiceAllocation()
        {
            HospitalGateway hospitalGateway = new HospitalGateway();
            var serviceAllocationList = hospitalGateway.GetHospitalServiceAllocations();
            return View(serviceAllocationList);
        }
        public JsonResult getThanaDropdownListByDistrictId(int DistrictId)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            if (DistrictId != 0)
            {
                DropDownGateway dropDownGateway = new DropDownGateway();
                list = dropDownGateway.getThanaDopdownListByDistrictId(DistrictId);
            }
            
            return Json(new SelectList(list, "Value", "Text"));
        }
        public JsonResult getLocationDropdownListByThanaId(int ThanaId)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            if (ThanaId != 0)
            {
                DropDownGateway dropDownGateway = new DropDownGateway();
                list = dropDownGateway.getLocationDopdownListByThanaId(ThanaId);
            }
            
            return Json(new SelectList(list, "Value", "Text"));
        }
        public JsonResult geHospitalListByThanaId(int ThanaId)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            if (ThanaId != 0)
            {
                DropDownGateway dropDownGateway = new DropDownGateway();
                list = dropDownGateway.getHospitalListByThanaId(ThanaId);
            }
           
            return Json(new SelectList(list, "Value", "Text"));
        }
	}
}

FindingAddress/Views/Hospital/saveHospital.cshtml
@model FindingAddress.Models.Hospital

@{
    ViewBag.Title = "saveHospital";
}

<h2>saveHospital</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hospital</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HospitalTypeId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.HospitalTypeId, ViewBag.HospitalTypeDropdownList as IEnumerable<SelectListItem>, "SELECT", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HospitalTypeId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DivisionId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DivisionId, ViewBag.DivisionList as IEnumerable<SelectListItem>, "SELECT", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DivisionId)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DistrictId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="DistrictId" class="form-control" name="DistrictId">
                    <option selected="selected">SELECT</option>
                </select>
                @Html.ValidationMessageFor(model => model.DistrictId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CityId, ViewBag.cityList as IEnumerable<SelectListItem>, "SELECT", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CityId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThanaId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="ThanaId" class="form-control" name="ThanaId">
                    <option selected="selected">SELECT</option>
                </select>
                @Html.ValidationMessageFor(model => model.ThanaId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="LocationId" class="form-control" name="LocationId">
                    <option selected="selected">SELECT</option>
                </select>
                @Html.ValidationMessageFor(model => model.LocationId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">
        $(document).ready(function () {
            $('#DivisionId').change(function () {
                $.ajax({
                    type: 'post',
                    url: '@Url.Action("getDistrictDropdownListByDivisionId")',
                    dataType: 'json',
                    data: { DivisionId: $("#DivisionId").val() },

                    success: function (data) {
                        $("#DistrictId").empty();
                        $("#DistrictId").append('<option value="' + 0 + '">' + "SELECT" + '</option>');
                        $(data).each(function (index, item) {

                            $("#DistrictId").append('<option value="' + item.Value + '">' + item.Text + '</option>');

                        });
                    }
                });
            });
        $('#DistrictId').change(function() {
            $.ajax({
                type: 'post',
                url: '@Url.Action("getThanaDropdownListByDistrictId")',
                dataType: 'json',
                data: { DistrictId: $("#DistrictId").val() },

                success: function(data) {
                    $("#ThanaId").empty();
                    $("#ThanaId").append('<option value="' + 0 + '">' + "SELECT" + '</option>');
                    $(data).each(function(index, item) {

                        $("#ThanaId").append('<option value="' + item.Value + '">' + item.Text + '</option>');

                    });
                }
            });
        });
        $('#ThanaId').change(function() {
            $.ajax({
                type: 'post',
                url: '@Url.Action("getLocationDropdownListByThanaId")',
                dataType: 'json',
                data: { ThanaId: $("#ThanaId").val() },

                success: function(data) {
                    $("#LocationId").empty();
                    $("#LocationId").append('<option value="' + 0 + '">' + "SELECT" + '</option>');
                    $(data).each(function(index, item) {

                        $("#LocationId").append('<option value="' + item.Value + '">' + item.Text + '</option>');

                    });
                }
            });

        });

    })
</script>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FindingAddress/Views/Hospital/saveHospitalService.cshtml
@model FindingAddress.Models.HospitalService

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>saveHospitalService</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>HospitalService</h4>
            <hr />
            @Html.ValidationSummary(true)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

FindingAddress/Views/Hospital/saveHospitalServiceAllocation.cshtml
@model FindingAddress.Models.HospitalServiceAllocation

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>saveHospitalServiceAllocation</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        <h3 style="text-align: center; color: red">@ViewBag.result</h3>
        <div class="form-horizontal">
            <h4>HospitalServiceAllocation</h4>
            <hr />
            @Html.ValidationSummary(true)
    
            <div class="form-group">
                @Html.LabelFor(model => model.DivisionId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.DivisionId, ViewBag.DivisionList as IEnumerable<SelectListItem>, "SELECT", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DivisionId)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DistrictId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <select id="DistrictId" class="form-control" name="DistrictId">
                        <option selected="selected">SELECT</option>
                    </select>
                    @Html.ValidationMessageFor(model => model.DistrictId)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ThanaId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <select id="ThanaId" class="form-control" name="ThanaId">
                        <option selected="selected">SELECT</option>
                    </select>
                    @Html.ValidationMessageFor(model => model.ThanaId)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HospitalId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <select id="HospitalId" class="form-control" name="HospitalId">
                        <option selected="selected">SELECT</option>
                    </select>
                    @Html.ValidationMessageFor(model => model.HospitalId)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ServiceId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.ServiceId, ViewBag.ServiceList as IEnumerable<SelectListItem>, "SELECT", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ServiceId)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.EstimatedPrice, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.EstimatedPrice, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.EstimatedPrice)
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#DivisionId').change(function () {
                $.ajax({
                    type: 'post',
                    url: '@Url.Action("getDistrictDropdownListByDivisionId")',
                    dataType: 'json',
                    data: { DivisionId: $("#DivisionId").val() },

                    success: function (data) {
                        $("#DistrictId").empty();
                        $("#DistrictId").append('<option value="' + 0 + '">' + "SELECT" + '</option>');
                        $(data).each(function (index, item) {

                            $("#DistrictId").append('<option value="' + item.Value + '">' + item.Text + '</option>');

                        });
                    }
                });
            });
        $('#DistrictId').change(function() {
            $.ajax({
                type: 'post',
                url: '@Url.Action("getThanaDropdownListByDistrictId")',
                dataType: 'json',
                data: { DistrictId: $("#DistrictId").val() },

                success: function(data) {
                    $("#ThanaId").empty();
                    $("#ThanaId").append('<option value="' + 0 + '">' + "SELECT" + '</option>');
                    $(data).each(function(index, item) {

                        $("#ThanaId").append('<option value="' + item.Value + '">' + item.Text + '</option>');

                    });
                }
            });
        });
        $('#ThanaId').change(function() {
            $.ajax({
                type: 'post',
                url: '@Url.Action("geHospitalListByThanaId")',
                dataType: 'json',
                data: { ThanaId: $("#ThanaId").val() },

                success: function(data) {
                    $("#HospitalId").empty();
                    $("#HospitalId").append('<option value="' + 0 + '">' + "SELECT" + '</option>');
                    $(data).each(function(index, item) {

                        $("#HospitalId").append('<option value="' + item.Value + '">' + item.Text + '</option>');

                    });
                }
            });

        });
    })
    </script>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

FindingAddress/Views/Hospital/saveHospitalType.cshtml
@model FindingAddress.Models.HospitalType

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>saveHospitalType</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>HospitalType</h4>
            <hr />
            @Html.ValidationSummary(true)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description)
                    @Html.ValidationMessageFor(model => model.Description)
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

FindingAddress/Views/Hospital/showHospitaType.cshtml
@model IEnumerable<FindingAddress.Models.HospitalType>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>showHospitaType</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

FindingAddress/Views/Hospital/showHospital.cshtml
@model IEnumerable<FindingAddress.Models.Hospital>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>showHospital</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HospitalTypeId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DivisionId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DistrictId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CityId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ThanaId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LocationId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HospitalTypeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DivisionId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DistrictId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CityId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThanaId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocationId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

FindingAddress/Views/Hospital/showHospitalService.cshtml
@model IEnumerable<FindingAddress.Models.HospitalService>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>showHospitalService</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "saveHospitalService","Hospital")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

FindingAddress/Views/Hospital/showHospitalServiceAllocation.cshtml
@model IEnumerable<FindingAddress.Models.HospitalServiceAllocation>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>showHospitalServiceAllocation</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "saveHospitalServiceAllocation","Hospital")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.HospitalId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ServiceId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstimatedPrice)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HospitalId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstimatedPrice)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>